package(default_visibility = ["//visibility:public"])

py_library(
    name = "__init__",
    srcs = ["__init__.py"],
    srcs_version = "PY3ONLY",
    deps = [],
)

py_library(
    name = "test_config",
    srcs = ["test_config.py"],
    srcs_version = "PY3ONLY",
)
