// Code generated by protoc-gen-go. DO NOT EDIT.
// source: videoData.proto

package util

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VideoToRead struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FrameCount           int32    `protobuf:"varint,2,opt,name=frameCount,proto3" json:"frameCount,omitempty"`
	XRes                 int32    `protobuf:"varint,3,opt,name=xRes,proto3" json:"xRes,omitempty"`
	YRes                 int32    `protobuf:"varint,4,opt,name=yRes,proto3" json:"yRes,omitempty"`
	Frames               []*Frame `protobuf:"bytes,5,rep,name=frames,proto3" json:"frames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoToRead) Reset()         { *m = VideoToRead{} }
func (m *VideoToRead) String() string { return proto.CompactTextString(m) }
func (*VideoToRead) ProtoMessage()    {}
func (*VideoToRead) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b301bfbc7aa2f48, []int{0}
}

func (m *VideoToRead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoToRead.Unmarshal(m, b)
}
func (m *VideoToRead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoToRead.Marshal(b, m, deterministic)
}
func (m *VideoToRead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoToRead.Merge(m, src)
}
func (m *VideoToRead) XXX_Size() int {
	return xxx_messageInfo_VideoToRead.Size(m)
}
func (m *VideoToRead) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoToRead.DiscardUnknown(m)
}

var xxx_messageInfo_VideoToRead proto.InternalMessageInfo

func (m *VideoToRead) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *VideoToRead) GetFrameCount() int32 {
	if m != nil {
		return m.FrameCount
	}
	return 0
}

func (m *VideoToRead) GetXRes() int32 {
	if m != nil {
		return m.XRes
	}
	return 0
}

func (m *VideoToRead) GetYRes() int32 {
	if m != nil {
		return m.YRes
	}
	return 0
}

func (m *VideoToRead) GetFrames() []*Frame {
	if m != nil {
		return m.Frames
	}
	return nil
}

type VideoToWrite struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FrameCount           int32    `protobuf:"varint,2,opt,name=frameCount,proto3" json:"frameCount,omitempty"`
	XRes                 int32    `protobuf:"varint,3,opt,name=xRes,proto3" json:"xRes,omitempty"`
	YRes                 int32    `protobuf:"varint,4,opt,name=yRes,proto3" json:"yRes,omitempty"`
	Frames               []*Frame `protobuf:"bytes,5,rep,name=frames,proto3" json:"frames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoToWrite) Reset()         { *m = VideoToWrite{} }
func (m *VideoToWrite) String() string { return proto.CompactTextString(m) }
func (*VideoToWrite) ProtoMessage()    {}
func (*VideoToWrite) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b301bfbc7aa2f48, []int{1}
}

func (m *VideoToWrite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoToWrite.Unmarshal(m, b)
}
func (m *VideoToWrite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoToWrite.Marshal(b, m, deterministic)
}
func (m *VideoToWrite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoToWrite.Merge(m, src)
}
func (m *VideoToWrite) XXX_Size() int {
	return xxx_messageInfo_VideoToWrite.Size(m)
}
func (m *VideoToWrite) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoToWrite.DiscardUnknown(m)
}

var xxx_messageInfo_VideoToWrite proto.InternalMessageInfo

func (m *VideoToWrite) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *VideoToWrite) GetFrameCount() int32 {
	if m != nil {
		return m.FrameCount
	}
	return 0
}

func (m *VideoToWrite) GetXRes() int32 {
	if m != nil {
		return m.XRes
	}
	return 0
}

func (m *VideoToWrite) GetYRes() int32 {
	if m != nil {
		return m.YRes
	}
	return 0
}

func (m *VideoToWrite) GetFrames() []*Frame {
	if m != nil {
		return m.Frames
	}
	return nil
}

type Frame struct {
	Vals                 []int32  `protobuf:"varint,6,rep,packed,name=vals,proto3" json:"vals,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Frame) Reset()         { *m = Frame{} }
func (m *Frame) String() string { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()    {}
func (*Frame) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b301bfbc7aa2f48, []int{2}
}

func (m *Frame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Frame.Unmarshal(m, b)
}
func (m *Frame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Frame.Marshal(b, m, deterministic)
}
func (m *Frame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frame.Merge(m, src)
}
func (m *Frame) XXX_Size() int {
	return xxx_messageInfo_Frame.Size(m)
}
func (m *Frame) XXX_DiscardUnknown() {
	xxx_messageInfo_Frame.DiscardUnknown(m)
}

var xxx_messageInfo_Frame proto.InternalMessageInfo

func (m *Frame) GetVals() []int32 {
	if m != nil {
		return m.Vals
	}
	return nil
}

func init() {
	proto.RegisterType((*VideoToRead)(nil), "util.VideoToRead")
	proto.RegisterType((*VideoToWrite)(nil), "util.VideoToWrite")
	proto.RegisterType((*Frame)(nil), "util.frame")
}

func init() {
	proto.RegisterFile("videoData.proto", fileDescriptor_9b301bfbc7aa2f48)
}

var fileDescriptor_9b301bfbc7aa2f48 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0xcb, 0x4c, 0x49,
	0xcd, 0x77, 0x49, 0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x29, 0x2d, 0xc9,
	0xcc, 0x51, 0xea, 0x62, 0xe4, 0xe2, 0x0e, 0x03, 0xc9, 0x84, 0xe4, 0x07, 0xa5, 0x26, 0xa6, 0x08,
	0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x31, 0x65, 0xa6, 0x08,
	0xc9, 0x71, 0x71, 0xa5, 0x15, 0x25, 0xe6, 0xa6, 0x3a, 0xe7, 0x97, 0xe6, 0x95, 0x48, 0x30, 0x81,
	0xc5, 0x91, 0x44, 0x84, 0x84, 0xb8, 0x58, 0x2a, 0x82, 0x52, 0x8b, 0x25, 0x98, 0xc1, 0x32, 0x60,
	0x36, 0x48, 0xac, 0x12, 0x24, 0xc6, 0x02, 0x11, 0x03, 0xb1, 0x85, 0x94, 0xb9, 0xd8, 0xc0, 0xba,
	0x8a, 0x25, 0x58, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0xb8, 0xf5, 0x40, 0xd6, 0xeb, 0x81, 0xc5, 0x82,
	0xa0, 0x52, 0x4a, 0xdd, 0x8c, 0x5c, 0x3c, 0x50, 0xc7, 0x84, 0x17, 0x65, 0x96, 0xa4, 0x0e, 0xac,
	0x6b, 0xe4, 0xb9, 0x58, 0xc1, 0x2c, 0x21, 0x31, 0x2e, 0x96, 0xb2, 0xc4, 0x9c, 0x62, 0x09, 0x36,
	0x05, 0x66, 0x0d, 0x56, 0x27, 0x26, 0x01, 0xc6, 0x20, 0x30, 0x3f, 0x89, 0x0d, 0x1c, 0x90, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x15, 0x89, 0x4e, 0x2c, 0x5b, 0x01, 0x00, 0x00,
}
