
package(default_visibility = ["//visibility:public"])

py_library(
    name = "fyre",
    srcs = ["fyre.py"],
)

py_test(
    name = "fyre_test",
    srcs = ["fyre_test.py"],
    deps = [
        "//tools/fyre:fyre"
    ],
)
