
package(default_visibility = ["//visibility:public"])

py_library(
    name = "pcrun",
    srcs = ["pcrun.py"],
)

py_test(
    name = "pcrun_test",
    srcs = ["pcrun_test.py"],
    deps = [
        "//tools/environments:pcrun"
    ],
)
