
package(default_visibility = ["//visibility:public"])

py_library(
    name = "__init__",
    srcs = ["__init__.py"],
    deps = [
        "//pcml/datasets:affectnet",
        "//pcml/datasets:celeba",
        "//pcml/datasets:deap",
        "//pcml/datasets:fec",
        "//pcml/datasets:vggface2",
        "//pcml/datasets:vox_celeb_cbt",
        "//pcml/models:dev",
        "//pcml/models:modality_correspondence",
        "//pcml/models:percep_similarity_emb",
    ],
)

py_library(
    name = "test_config",
    srcs = ["test_config.py"],
)
