name: FTW Deploy Study
on:
  push:
    branches:
      - 'ftw-user-ingress-fns'
      - 'studies/**'
jobs:
  notify-start:
    name: Notify start
    runs-on: ubuntu-latest
    steps:
      - name: Slack notify triggered study deployment
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: \'{\"channel\":\"CTZV73MMK\",\"text\":\"A study deployment was initiated.\"}\'
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
        id: deploy
      - name: Install Dependencies
        run: cd ftw/ftw_ui && yarn install
      - name: Build
        run: cd ftw/ftw_ui && yarn run build:firebase
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: ftw/ftw_ui/build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
        id: deploy
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: ftw/ftw_ui/build
      - name: Set project
        uses: w9jds/firebase-action@master
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          PROJECT_PATH: ftw/ftw_ui
        with:
          args: use --add clarify
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          PROJECT_PATH: ftw/ftw_ui
  notify-complete:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Notify slack
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: \'{\"channel\":\"CTZV73MMK\",\"text\":\"A study deployment succeeded, here's the URL.\"}\'
  notify-deployment-failed:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Notify slack
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: \'{\"channel\":\"CTZV73MMK\",\"text\":\"A study deployment failed.\"}\'
